name: Build and Release JavaJiggle

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build Windows EXE
        run: |
          pyinstaller --noconfirm --onefile --windowed `
            --icon=assets/JavaJiggle_icon.ico `
            --version-file=version.txt `
            --name=JavaJiggle gui.py

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/JavaJiggle.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build macOS App
        run: |
          pyinstaller --noconfirm --windowed \
            --icon=assets/JavaJiggle_icon.icns \
            --name=JavaJiggle gui.py

      - name: Upload .app to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/JavaJiggle.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
